### ISSUE TITLE
Create a one command install of Infra Agent and Logging for Windows

### ISSUE THREAD

**Issue by rishimukhop1** [newrelic/open-install-library#102]
This entails installation of the infrastructure agent and allowing configuration of logging in a Windows environment, with the same general experiences as the Linux flow.

Aha! Link: https://newrelic.aha.io/features/VIRTUOSO-23

**Comment by Julien4218** [comment]
PR for this work https://github.com/newrelic/open-install-library/pull/103

**Comment by Julien4218** [comment]
@sheilakrishnan and @rishimukhop1 I believe this work is completed and this issue should be closed.
