### ISSUE TITLE
mysql not supported on Ubuntu 24.04

### ISSUE THREAD

**Issue by burner1024** [newrelic/open-install-library#1125]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

mysql-open-source-integration  (unsupported) 

## Steps to Reproduce

Try to install mysql integration on Ubuntu 24.04

## Expected Behavior

Working mysql integration on Ubuntu 24.04

## Relevant Logs / Console output

> mysql-open-source-integration  (unsupported) 

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

Ubuntu 24.04
[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

If it'd print WHY it's unsupported, that would save a lot of time.

**Comment by vagrawal-newrelic** [comment]
Thank you very much  @burner1024 for bringing this issue to our attention. We appreciate your patience and feedback.

We are pleased to inform you that the MySQL integration support for Ubuntu 24.04 has been successfully released in version 0.96.2 of our CLI. This update includes several enhancements and fixes to ensure compatibility  on Ubuntu 24.04.
Please update to the latest version of our CLI to take advantage of these improvements

**Comment by burner1024** [comment]
Nope, not working.
```
TASK [newrelic.newrelic_install : Report install script output] ***********************************************************************************************************************************************
ok: [aws1] => {
    "install_script.stdout_lines": [
        "Installing New Relic CLI v0.96.2",
        "Installing to /usr/local/bin"
    ]
}
...
TASK [newrelic.newrelic_install : Report incomplete installs] *************************************************************************************************************************************************
ok: [aws1] => {}

MSG:

{'status': 'INCOMPLETE', 'node': 'xxx', 'summary': ['  Installation Summary', '', '  ✔  Infrastructure Agent  (installed)  ', '  ✔  Logs Integration  (installed)  ', '  ✔  NGINX Integration  (installed)  ', '  ✔  PHP Agent  (installed)  ', '  ⊘  MySQL Integration  (unsupported)  ', '', '  Installation was successful overall, however, one or more installations could not be completed.', '  Follow the instructions at the URL below to complete the installation process. ', '', '  ⮕  https://onenr.io/xxx', '', '  View your logs at the link below:', '  ⮕  https://onenr.io/xxx', '', '  --------------------', '', '', 'We encountered an issue during the installation: one or more selected recipes could not be installed.', 'If this problem persists, visit the documentation and support page for additional help here at https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/get-started/requirements-infrastructure-agent/']}
```

**Comment by vagrawal-newrelic** [comment]
Hii @burner1024,
Thank you for reporting this issue. I attempted to reproduce the problem, but I was able to successfully instrument the MySQL integration on Ubuntu 24.04. It is possible that the issue might be related to the MySQL version you are using or some other system configuration issue.

Could you please provide the version of MySQL you are currently using? This information will help us diagnose the issue more effectively.

For testing the instrumentation I have used the below environment configuration:
**OS version**: Ubuntu-24.04
**mysql version:**  mysql  Ver 8.0.39-0ubuntu0.24.04.2 for Linux on x86_64 ((Ubuntu))
**Status of instrumentation**: Success
<img width="772" alt="image" src="https://github.com/user-attachments/assets/9d33b815-87a5-4fa9-9385-1a48347120fd">


Can you also run the command with --debug flag and share the debug logs as it will help us to diagnose further. Also when the instrumentation fails you will get a prompt to share logs with newrelic, So please select yes for the prompt!
Thank you for your cooperation.

**Comment by burner1024** [comment]
```
ERROR Unsupported (MySQL Integration): Unable to match any of the following processes: 
- mysqld
```

```
ps axuw | grep mysql
mysql    3616188  0.3  8.9 1585512 353208 ?      Ssl  Oct16  76:34 /usr/sbin/mariadbd
```
