### ISSUE TITLE
Create Linux Oracle Recipe

### ISSUE THREAD

**Issue by jbeveland27** [newrelic/open-install-library#191]
Documentation:
https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/oracle-database-monitoring-integration

For Logging: Ensure that common log file directories/patterns & process name for Oracle are populated in the beginning of the recipe.

**Comment by JakubKotkowiak** [comment]
This ticket is blocked by the instance size, there's not enough space to install and setup oracle db.
