### ISSUE TITLE
Create Windows HAProxy Recipe

### ISSUE THREAD

**Issue by setamyDG** [newrelic/open-install-library#238]
Documentation: [https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/haproxy-monitoring-integration](https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/haproxy-monitoring-integration)

Necessary Configuration:

- **Username:** (Prompt User)
- **Password:** (Prompt User)
- **Stats URL:** (Prompt User)

Cluster name and remaining default values should be able to be kept as is in the configuration file.

**For Logging:** Ensure that common log file directories/patterns & process name for HAProxy is populated in the beginning of the recipe.

 Official website says: 
      HAProxy is known to reliably run on the following OS/Platforms :
      Linux 2.4 on x86, x86_64, Alpha, Sparc, MIPS, PARISC
      Linux 2.6-5.x on x86, x86_64, ARM, AARCH64, MIPS, Sparc, PPC64
      Solaris 8/9 on UltraSPARC 2 and 3
      Solaris 10 on Opteron and UltraSPARC
      FreeBSD 4.10 - current on x86
      OpenBSD 3.1 to -current on i386, amd64, macppc, alpha, sparc64 and VAX (check the ports)
      AIX 5.1 - 5.3 on Power™ architecture

**Comment by JakubKotkowiak** [comment]
Requires cygwin
