### ISSUE TITLE
Create Windows MongoDB Recipe

### ISSUE THREAD

**Issue by setamyDG** [newrelic/open-install-library#241]
[ **Documentation:** https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/mongodb-monitoring-integration](https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/mongodb-monitoring-integration)

**Output to user:**

**Note:** `These steps must be completed in order for the MongoDB integration to function properly. `

1. In the MongoDB shell, enter `use admin`.
2. Use the following command to create the `listCollections` role.

   ```

   db.createRole({<br/> role: "listCollections",<br/> privileges: [{<br/> resource: {db:"",collection:""},<br/> actions: ["listCollections"]<br/> }],<br/> roles: []<br/>})<br/>

   ```
3. ```

   Use the following commands to create a new user, and assign clusterMonitor and listCollections roles to the user.<br/>db.createUser({<br/> user: "username",<br/> pwd: "password",<br/> roles: [<br/> "clusterMonitor",<br/> "listCollections"<br/> ]<br/>})

   ```

   **Necessary Configuration:**

- **Cluster Name:** Prompt user to enter, assume there is no default
- **Username:** Prompt user to enter, assume there is no default
- **Password** : Prompt user to enter, assume there is no default
- **AuthSource** : Have user confirm default of `admin`
- **Host:** Have user confirm default of `localhost.` FYI: The recipe will need to set this variable to localhost if the user accepts the default. The hostname is not set to localhost in the downloaded configuration file with the integration.
- **Port:** Have user confirm default of `27017`
- **SSL:** Prompt: `Are you using SSL?``(Y/N)` If YES
  - `Please enter the path to your Certificate Authority file: `
  - `Would you like to verify the certificate sent by the host? Y/N ` IF YES
    - `Please enter the path to the Client certificate file, if required: `
    - `Please enter the passphrase to decrypt the PEM key file, if required:`

  Based on this input set the values, `ssl, ssl_insecure_skip_verify`, `ssl_ca_certs,` `pem_key_file` and `passphrase` in the YAML config file.

**For Logging:** Ensure that common log file directories/patterns & process name for MongoDB is populated in the beginning of the recipe.

**Comment by JakubKotkowiak** [comment]
This ticket as well as the PostgreSQL integration require passing of ' into the config file. After many attempts we have been unable to pass it correctly which is causing the config to be unusable.
