### ISSUE TITLE
ohi Memcached recipe on RHEL with -y flag

### ISSUE THREAD

**Issue by washu** [newrelic/open-install-library#326]
Im trying to automate the install of the recipe. passing a -y to assume yes i.e. all defaults fails.

/usr/local/bin/newrelic install -y -n memcached-open-source-integration

It should be successful

Error in the log complains that NR_CLI_USERNAME doesnt have a default.

Centos 7

N/A

**Comment by gabeobrien** [comment]
@washu Thanks for the bug report!  I think what you need to do is provide two ENV variable with your command:

`NR_CLI_DB_USERNAME=user_name  NR_CLI_DB_PASSWORD=password  /usr/local/bin/newrelic install -y -n memcached-open-source-integration`

With this change you should be able to get the installation working.  Let me know if you have any other issues!

You can see find the ENV vars here:
https://github.com/newrelic/open-install-library/blob/main/recipes/newrelic/infrastructure/ohi/memcached/rhel.yml#L47
