### ISSUE TITLE
dotnet-agent-installer does not install dotnet agent 

### ISSUE THREAD

**Issue by chuantan-myob** [newrelic/open-install-library#337]
## Description
The following script runs as part of our initialization script in EC2 UserData, from last week the script stopped working, from EC2 log, we can see powshell process didn't exit and there's no log either.
After logging into EC2 instance, we found New Relic agent was not installed, only cli installer was installed.

## Steps to Reproduce
Run this script as Administrator in powershell
```sh
 Write-Host "Install New Relic dotnet agent"
(New-Object System.Net.WebClient).DownloadFile("https://github.com/newrelic/newrelic-cli/releases/latest/download/NewRelicCLIInstaller.msi", "$env:TEMP\NewRelicCLIInstaller.msi")
msiexec.exe /qn /i $env:TEMP\NewRelicCLIInstaller.msi | Out-Null
$env:NEW_RELIC_API_KEY = $apiKey
$env:NEW_RELIC_ACCOUNT_ID = $accountId
$env:NEW_RELIC_ASSUME_YES = "true"
& 'C:\Program Files\New Relic\New Relic CLI\newrelic.exe' install -n dotnet-agent-installer 
```

## Expected Behavior
Dotnet agent and infrastructure agent should be installed 

## Relevant Logs / Console output
```
# I have tried running the script as Admin, it's stuck at this screen:
==> Installing dotnet-agent-installer...

================================================================================
=                                                                              =
=                                   Warning                                    =
=                                                                              =
=       This installation will automatically restart IIS upon completion.      =
=                                                                              =
================================================================================

If you are not hosting your .NET application using IIS please see our other installation options:
https://docs.newrelic.com/docs/agents/net-agent/installation/install-net-agent-windows/.

 
```

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

* Windows Server 2016
* IIS 10.0

**Comment by Julien4218** [comment]
Thanks @chuantan-myob for reporting this.
I see the command is attempting to use the assume yes. You can actually do this by just adding the newrelic-cli option -y
If you could, please try that out with setting the environment variable $env:NEW_RELIC_ASSUME_YES.

**Comment by chuantan-myob** [comment]
It worked after I added `option -y`.
```
& 'C:\Program Files\New Relic\New Relic CLI\newrelic.exe' install -n dotnet-agent-installer option -y 
```

This original script was copied from New Relic guideline and it has been working till last week. `$env:NEW_RELIC_ASSUME_YES` was added when I checked the git commit.

**Comment by Julien4218** [comment]
Interesting, if you can reference the New Relic guideline you used, we might have to update them.

Also, you don't need the word "option" in the command line, you just need the -y for non interactive, so it should look like this

& 'C:\Program Files\New Relic\New Relic CLI\newrelic.exe' install -n dotnet-agent-installer -y

**Comment by chuantan-myob** [comment]
The script is showed when you click **Add .Net Data** button in this page `https://docs.newrelic.com/docs/agents/net-agent/installation/introduction-net-agent-install/`
