### ISSUE TITLE
Create Linux recipe for Cassandra

### ISSUE THREAD

**Issue by rishimukhop1** [newrelic/open-install-library#53]
**Documentation:** [https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/cassandra-monitoring-integration](https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/cassandra-monitoring-integration).

**Necessary Configuration** :

- **Username:** (Prompt user to enter)
- **Password:** (Prompt user to enter)
- **Hostname:** (Allow user to confirm default of localhost, or enter new value)
- **Port:** (Allow user to confirm default port of 9042, or enter new value).

Note: The default cassandra port is different in our docs and base config file, and this is not the default port that Cassandra runs with. We should use the 9042 default in our version of the config file.

**For Logging:** Ensure that common log file directories/patterns & process name for Cassandra is populated in the beginning of the recipe.

Aha! Link: https://newrelic.aha.io/features/VIRTUOSO-47

**Comment by Julien4218** [comment]
@sheilakrishnan and @rishimukhop1 I believe this work is completed, and this issue should be closed.
