### ISSUE TITLE
The ElasticSearch validationNrql is returning false negatives

### ISSUE THREAD

**Issue by murphpdx** [newrelic/open-install-library#573]
## Description

The ElasticSearch validationNrql will never find a match because the `WHERE` clause is comparing the `hostname` field. The `ElasticsearchClusterSample` table uses `label.host`.  So the query should be changed from `WHERE hostname LIKE '{{.HOSTNAME}}'` to `WHERE label.host LIKE '{{.HOSTNAME}}'`.

https://github.com/newrelic/open-install-library/blob/main/recipes/newrelic/infrastructure/ohi/elasticsearch/debian.yml#L33

**Comment by murphpdx** [comment]
It seems like java should be `host.displayName`?

https://github.com/newrelic/open-install-library/blob/main/recipes/newrelic/apm/java/linux.yml#L97

**Comment by fradvic** [comment]
We are no longer using hostname as a part of our validation query.
