### ISSUE TITLE
Create Linux HashiCorp Consul Recipe

### ISSUE THREAD

**Issue by rishimukhop1** [newrelic/open-install-library#58]
**Documentation:** [https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/hashicorp-consul-monitoring-integration](https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/hashicorp-consul-monitoring-integration)

Display to user: If using ACL, the credentials for the Consul integration must have the following policies: `agent:read`, `node:read`, and `service:read`.

**Necessary Configuration for Prompting:**

- **Hostname:** (Have user confirm default of localhost, enter new hostname if desired)
- **Port: (** Have user confirm default port of 8500, or enter new).
- **Token:** Prompt user: \_If you're using an ACL Token for authentication, please enter the token: else press [Enter] to continue. \_If the user leaves this entry blank by pressing enter, do not populate the token field in the sample YAML file.
- Prompt user,\_ Are you using SSL (y/n). \_
  - IF YES-
  - Set **enable\_ssl** configuration parameter to true.
  - Prompt User: _Would you like to trust the server certificate? (y/n)_
  - If Yes- No further action necessary
  - IF No- Prompt user for the **ca\_bundle\_dir** or the **ca\_bundle file** by saying: \_Please enter the certificate authority bundle directory or file. \_
  - If NO- No further action is needed

**For Logging:** Ensure that common log file directories/patterns & process name for HashiCorp Consul is populated in the beginning of the recipe.

Update from sheila 1/7/2021 - Asking CC to pause on this work. Low priorioty for Virtuosos engineers to help with this.

Aha! Link: https://newrelic.aha.io/features/VIRTUOSO-52

**Comment by jbeveland27** [comment]
Closed by https://github.com/newrelic/open-install-library/commit/47f7abf4fffe69180de85aaf96075b4f04d6a3df and https://github.com/newrelic/open-install-library/commit/9b8a4f31cdcd905687f94c5788d9fea8ffa7a225
