### ISSUE TITLE
Create Linux MongoDB Recipe

### ISSUE THREAD

**Issue by rishimukhop1** [newrelic/open-install-library#62]
[ **Documentation:** https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/mongodb-monitoring-integration](https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/mongodb-monitoring-integration)

**Output to user:**

**Note:** `These steps must be completed in order for the MongoDB integration to function properly. `

1. In the MongoDB shell, enter `use admin`.
2. Use the following command to create the `listCollections` role.

   ```

   db.createRole({<br/> role: "listCollections",<br/> privileges: [{<br/> resource: {db:"",collection:""},<br/> actions: ["listCollections"]<br/> }],<br/> roles: []<br/>})<br/>

   ```
3. ```

   Use the following commands to create a new user, and assign clusterMonitor and listCollections roles to the user.<br/>db.createUser({<br/> user: "username",<br/> pwd: "password",<br/> roles: [<br/> "clusterMonitor",<br/> "listCollections"<br/> ]<br/>})

   ```

   **Necessary Configuration:**

- **Cluster Name:** Prompt user to enter, assume there is no default
- **Username:** Prompt user to enter, assume there is no default
- **Password** : Prompt user to enter, assume there is no default
- **AuthSource** : Have user confirm default of `admin`
- **Host:** Have user confirm default of `localhost.` FYI: The recipe will need to set this variable to localhost if the user accepts the default. The hostname is not set to localhost in the downloaded configuration file with the integration.
- **Port:** Have user confirm default of `27017`
- **SSL:** Prompt: `Are you using SSL?``(Y/N)` If YES
  - `Please enter the path to your Certificate Authority file: `
  - `Would you like to verify the certificate sent by the host? Y/N ` IF YES
    - `Please enter the path to the Client certificate file, if required: `
    - `Please enter the passphrase to decrypt the PEM key file, if required:`

  Based on this input set the values, `ssl, ssl_insecure_skip_verify`, `ssl_ca_certs,` `pem_key_file` and `passphrase` in the YAML config file.

**For Logging:** Ensure that common log file directories/patterns & process name for MongoDB is populated in the beginning of the recipe.

Aha! Link: https://newrelic.aha.io/features/VIRTUOSO-56

**Comment by setamyDG** [comment]
Hello @rishimukhop1 ,
Regarding MongoDB recipe, we have a question about configuration. In docs it says we have 3 options how to send data.

![image](https://user-images.githubusercontent.com/37123078/105721030-67363800-5f24-11eb-91ae-c210e5d52b7b.png)

The question is: should we pick only "all" command or all 3 commands?

**Comment by devfreddy** [comment]
@rishimukhop1 I'm thinking `all` is the most appropriate place to start, and perhaps we expand the recipe in some future state to allow customizing that?

**Comment by setamyDG** [comment]
One more question, regarding the filters section of config, should we input it as another input variable or not? Right now if we leave it as is, it doesn't seem to work. Once we change it to `filters: '{"admin":null}'` it seems to be working.

**Comment by jbeveland27** [comment]
Closed by https://github.com/newrelic/open-install-library/commit/c2a4c396416e2c4b5ddb93ad07cba69ccaa12caa and https://github.com/newrelic/open-install-library/commit/46c8bf090ef5c1081240661f80248cad4d545b68
