### ISSUE TITLE
Create Linux MySQL Recipe

### ISSUE THREAD

**Issue by rishimukhop1** [newrelic/open-install-library#63]
[ **Documentation:** https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/mysql-monitoring-integration](https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/mysql-monitoring-integration)

Output to user when the recipe is executed:

\_ **Note:** \_\_ You need to have a MySQL user with replication permissions for enabling this integration. If you’d like to create a new user please use these commands as reference. \_

_sudo mysql -e "CREATE USER 'newrelic'@'localhost' IDENTIFIED BY \ __'YOUR\_SELECTED\_PASSWORD';\__"_

_sudo mysql -e "GRANT REPLICATION CLIENT ON \*.\* TO 'newrelic'@'localhost' WITH MAX\_USER\_CONNECTIONS 5;"_

**<br/>Necessary Configuration**<br/>Allow the user to confirm the defaults line by line or change if necessary.

- Username (No default, have user enter)
- Password (No default have user enter)
- Hostname (default is localhost, have user confirm or enter a new hostname)
- Port (default is 3306, have user confirm or enter a new hostname)

**For Logging:** Ensure that common log file directories/patterns & process name for MySQL is populated in the beginning of the recipe.

This recipe needs to also be plugged into the testing framework and the according test file definitions must be written.

Aha! Link: https://newrelic.aha.io/features/VIRTUOSO-57

**Comment by JakubKotkowiak** [comment]
Hello, We've got a question regarding the tickets present on this board. We could see the links to Aha! but we do not seem to have an access to it. Is it something that would be provided to us in the near future or is the information provided in the ticket + documentation enough?

**Comment by Julien4218** [comment]
@sheilakrishnan and @rishimukhop1 I believe this work is completed. We should close this issue.
