### ISSUE TITLE
Create Linux PostgresSQL Recipe

### ISSUE THREAD

**Issue by rishimukhop1** [newrelic/open-install-library#66]
**Documentation:** [ **https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration** ](https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration)

**Output to user:**

`Note:In order for this integration to function you need to either create or have an existing user with READ Permissions on pg_stat_database, pg_stat_database_conflicts and pg_stat_bgwriter.`

`If you'd like to create a new user with these permissions please follow these steps within your PostgresSQL Instance:`

` CREATE USER new_relic WITH PASSWORD 'PASSWORD';<br/>GRANT SELECT ON pg_stat_database TO new_relic;<br/>GRANT SELECT ON pg_stat_database_conflicts TO new_relic;<br/>GRANT SELECT ON pg_stat_bgwriter TO new_relic; `

**Required Configuration:**

- **Username:** Prompt User, assume no default value is provided
- **Password:** Prompt User, assume no default value is provided
- **Port:** Have user confirm the default port of **5432,** or allow change **.** Note: In the recipe the default will still require a change to the config file. The downloaded config file contains a different port.
- **Database:** Have user confirm default of postgres or allow change
- **SSL** : `Would you like to configure SSL? Y/N` **IF YES**
  - `Please provide the path of the client certificate file :`
  - `Please provide the path of the client key file:`
  - `Trust the server certificate? Y/N` IF NO
  - `Please provide the path for the root certificate file:`
- Set **collections\_list to ALL in recipe** (no user prompting required)
- **Set pgbouncer to true** (no user prompting required)

**For Logging:** Ensure that common log file directories/patterns & process name for Postgres SQL are populated in the beginning of the recipe.

Aha! Link: https://newrelic.aha.io/features/VIRTUOSO-60

**Comment by jbeveland27** [comment]
Closed by https://github.com/newrelic/open-install-library/commit/d63fd9d5bf907b78dc49b92571aeca8084e52462 and https://github.com/newrelic/open-install-library/commit/07c3e30492a84317fd8407adc3eb1e35476ae8fc
