### ISSUE TITLE
Create Windows Perfmon Recipe

### ISSUE THREAD

**Issue by rishimukhop1** [newrelic/open-install-library#67]
[https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/perfmon-integration](https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/perfmon-integration)

Aha! Link: https://newrelic.aha.io/features/VIRTUOSO-61

**Comment by sarvesha-jaiswal** [comment]
can you explain the issue, i want to work on it ?
