### ISSUE TITLE
Create Linux Rabbit MQ Recipe

### ISSUE THREAD

**Issue by rishimukhop1** [newrelic/open-install-library#69]
**Documentation:** [ **https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/rabbitmq-monitoring-integration** ](https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/rabbitmq-monitoring-integration)

**Required Configuration** :

- **Username:** Prompt User, assume no default value is provided
- **Password:** Prompt User, assume no default value is provided
- **Hostname:** Allow user to confirm default of localhost
- **Port:** Allow user to configure default of 15672
- **Configuration Path:** Prompt user `Please enter your RabbitMQ Configuration File Path:`, assume no default is provided
- **Queues:** Prompt User `Please enter a comma separated list of the queue names you'd like to collect data from:`
- **Exhanges:** Prompt User: `If desired, please enter a comma separated list of the exchanges you'd like to collect data from:`
- **Vhosts:** Prompt user: `if desired, please enter a comma separated list of the Vhosts you'd like to collect data from: `
- **SSL:** Prompt: `Would you like to configure SSL? Y/N` IF YES set **use\_ssl** to true then
  - Prompt: `Please enter the location of the SSL certificate file or directory:` Set **ca\_bundle\_dir or ca\_bundle\_file** accordingly.

**For Logging:** Ensure that common log file directories/patterns & process name for RabbitMQ are populated in the beginning of the recipe.

Aha! Link: https://newrelic.aha.io/features/VIRTUOSO-63

**Comment by JakubKotkowiak** [comment]
@rishimukhop1 hello, I think there's an error and the default port should be 5672 not 15672

**Comment by jbeveland27** [comment]
@JakubKotkowiak The default port for RabbitMQ is 5672, but the integration connects to the [RabbitMQ Management Plugin](https://www.rabbitmq.com/management.html#usage-ui), which is on port 15672 by default.

**Comment by jbeveland27** [comment]
Also, we should add a `assert_pre_req`/`create_user_notification` task that performs checks and displays some of the prereqs in this part of the documentation. Specifically:

Checks:
* RabbitMQ Management Plugin is configured
* RabbitMQ command line tool, rabbitmqctl, in the PATH of the root user.
* Infrastructure Agent installed / running

The output message can look like this (I _think_ these emojis work as is, but will need to confirm with our designer):
> Note: In order for this integration to work, you must have:
> ✅ RabbitMQ Management Plugin configured
> ❌ RabbitMQ command line tool, rabbitmqctl, in the PATH of the root user.
> ✅ The New Relic Infrastructure Agent installed and newrelic-infra.service enabled.

I need to do some checking with the team to land on a standard pattern for us to do these checks/assertions to the user and figure out where that fits in the CLI UX. For now, I think adding the above messaging will suffice.

![image](https://user-images.githubusercontent.com/6722433/106761871-3d0b0700-6603-11eb-8d3e-4aed9f381b42.png)
