### ISSUE TITLE
Create Linux Redis Recipe

### ISSUE THREAD

**Issue by rishimukhop1** [newrelic/open-install-library#70]
Documentation: [https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/redis-monitoring-integration#keyspace-config](https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/redis-monitoring-integration#keyspace-config)

**Note for Engineer:** This documentation seems to be outdated for this OHI and differs materially from the sample configuration file provided. The OHI specification is written according to product management best intuition, and therefore the recipe may require adjustment based on testing.

**Required Configuration:**

- **Hostname:** Have user confirm default of **localhost** , or allow change
- **Port:** Have user confirm default of **6379** , or allow change.

Hostname and port in both sections, redis-metrics and redis-invetory in the config file can be set based on the above values.

- **Password:** Prompt `Please enter a password if your Redis server is password protected:`
- **Keys:** Prompt`If you would like to see metrics related to the length of selected keys, please enter the keys as a comma separated list in the following format `_`0:KEY_1, 1:KEY_2:`_

**For Logging:** Ensure that common log file directories/patterns & process name for Redis are populated in the beginning of the recipe.

Aha! Link: https://newrelic.aha.io/features/VIRTUOSO-64

**Comment by JakubKotkowiak** [comment]
@rishimukhop1 Am I correct that the default port provided in the ticket description is a typo? The default redis port is 6379 afaik

**Comment by rishimukhop1** [comment]
Good catch @JakubKotkowiak. Yes it is a typo and I have corrected it. thanks!!

**Comment by JakubKotkowiak** [comment]
Hello, we've attempted to prepare the SUSE integration for Redis but it's proving very problematic. For now according to what @rishimukhop1 stated we've laid it off and are concentrating on other recipes.

**Comment by jbeveland27** [comment]
Closed by https://github.com/newrelic/open-install-library/commit/a87c0d86201d949af6eb5a4aea1edb08e3cc15e7 and https://github.com/newrelic/open-install-library/commit/33f1674fb5021408d706a0f9d38913109967fd83
