### ISSUE TITLE
Create StatsD standard install recipe

### ISSUE THREAD

**Issue by rishimukhop1** [newrelic/open-install-library#72]
Documentation: [https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/statsd-monitoring-integration-version-2](https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/statsd-monitoring-integration-version-2)

Installing this integration should not require any user input.

- Check that Docker is installed, otherwise prompt:` Installation of StatsD requires Docker, please install Docker and re-run the installation using newrelic install <installation formula name>`
- Run the docker command in the install section with the appropriate Account ID and API Key. Note: We will need to check if we can use the CLI to give us this information.
- The appropriate Docker command needs to run based on the region.

**For Logging:** Ensure that common log file directories/patterns & process name for StatsD is populated in the beginning of the recipe.

Aha! Link: https://newrelic.aha.io/features/VIRTUOSO-66

**Comment by JakubKotkowiak** [comment]
Hello @rishimukhop1 @jbeveland27 @devfreddy @Julien4218,
We have a few questions regarding this integration:
- Regarding the values that have to be put in the docker command (Region, NR_ACCOUNT_ID, NR_INSERT_API_KEY) are all those fields available through the deployer? Regarding the first two we have seen them being used so we assume we can use them no problem but regarding the NR_INSERT_API_KEY we aren't really sure how we could go about using it in the docker command.
- Which entity should we be looking at? After looking at ContainerSample we could see some data arriving but we aren't sure if this is a correct entity for validationNrql
- Last one would be how we should be debugging the statsd integration run as a docker container? We have tried looking around inside the container but we couldn't really find a way to check the logs of the integration.
Hope to hear from you soon,
Jakub and Daniel

**Comment by jbeveland27** [comment]
Moving this issue back to the backlog until we have answers for these questions.
