### ISSUE TITLE
SQL Server 2014 not recognized

### ISSUE THREAD

**Issue by srafique2022** [newrelic/open-install-library#796]
SQL Server Integration is not working for SQL Server 2012/2014. Error saying SQL Server Integration is not supported.
However based on the documentation, it should support the SQL 2012/2014.

## Description

Noticed the failure of the install recipe to work with SQL Server 2014, that is why, filing an issue on GitHub

## Steps to Reproduce

Please refer to the support case for this issue --> https://newrelic-neworg.lightning.force.com/lightning/r/Case/5008W00000uckOkQAI/view

## Expected Behavior

Successfully integrate SQL Server 2012/2014.

## Relevant Logs / Console output

Images and files were attached to the support case.

**Comment by NRhzhao** [comment]
We released a fix for offline database that could've addressed this issue. Can you try again?
