### ISSUE TITLE
Provide idempotence guidance and best practices for OHI and Infra recipes

### ISSUE THREAD

**Issue by rishimukhop1** [newrelic/open-install-library#83]
Based on our understanding of idempotence needs, we need to provide some best practices on how to handle this within Infrastructure and OHI recipes. This will be helpful for external contributors to the Open Source Library, including our contractors. <br/><br/>Acceptance Criteria:

- Create a Readme/document within the Open Source Library that provides guidance on how to handle idempotence, and the best practices around it when creating OHI and Infra recipes.

Aha! Link: https://newrelic.aha.io/features/VIRTUOSO-82

**Comment by jbeveland27** [comment]
Closed by https://github.com/newrelic/open-install-library/commit/2864cfeff5bcadfcf0fec12e8026e0a542c38b84
