### ISSUE TITLE
'C:\Program Files\New Relic\New Relic CLI\newrelic.exe' install -n mssql-server-integration-installer  --debug --trace

### ISSUE THREAD

**Issue by reegankens** [newrelic/open-install-library#856]
{"error":"","guid":"","level":"debug","msg":"recipe event","recipe_name":"logs-integration","status":"INSTALLING","statusCount":5,"tasks":null,"time":"2023-01-23T07:55:52+07:00","validationDurationMs":0}
{"level":"debug","msg":"executing recipe logs-integration","time":"2023-01-23T07:55:53+07:00"}
{"level":"debug","msg":"no validationUrl defined, skipping","time":"2023-01-23T07:55:58+07:00"}
{"level":"debug","msg":"no validationNRQL defined, skipping","time":"2023-01-23T07:55:58+07:00"}
{"error":"","guid":"","level":"debug","msg":"recipe event","recipe_name":"logs-integration","status":"INSTALLED","statusCount":5,"tasks":null,"time":"2023-01-23T07:55:58+07:00","validationDurationMs":0}
{"level":"debug","msg":"Done executing and validating with progress for recipe name logs-integration.","time":"2023-01-23T07:56:00+07:00"}
{"level":"debug","msg":"Adding bundle recipe:mssql-server-integration-installer status:[{AVAILABLE 1647ms}] dependencies:[infrastructure-agent-installer]","time":"2023-01-23T07:56:00+07:00"}
{"level":"debug","msg":"Additional Targeted bundle recipes:{ADDITIONALTARGETED [{mssql-server-integration-installer [{AVAILABLE 1647ms}]}]}","time":"2023-01-23T07:56:00+07:00"}
{"error":"","guid":"","level":"debug","msg":"recipe event","recipe_name":"mssql-server-integration-installer","status":"AVAILABLE","statusCount":5,"tasks":null,"time":"2023-01-23T07:56:00+07:00","validationDurationMs":1647}
{"level":"debug","msg":"installing recipe","name":"mssql-server-integration-installer","time":"2023-01-23T07:56:01+07:00"}
{"level":"debug","msg":"preparing recipe","name":"mssql-server-integration-installer","time":"2023-01-23T07:56:01+07:00"}
{"error":"","guid":"","level":"debug","msg":"recipe event","recipe_name":"mssql-server-integration-installer","status":"INSTALLING","statusCount":5,"tasks":null,"time":"2023-01-23T07:56:01+07:00","validationDurationMs":0}
{"level":"debug","msg":"executing recipe mssql-server-integration-installer","time":"2023-01-23T07:56:03+07:00"}
{"level":"debug","msg":"sqlcmd with no credentials","time":"2023-01-23T07:56:08+07:00"}
{"level":"debug","msg":"no validationUrl defined, skipping","time":"2023-01-23T07:56:28+07:00"}
{"error":"encountered an error while validating receipt of data for mssql-server-integration-installer: timed out waiting for validation to succeed","guid":"","level":"debug","msg":"recipe event","recipe_name":"mssql-server-integration-installer","status":"FAILED","statusCount":5,"tasks":null,"time":"2023-01-23T08:01:28+07:00","validationDurationMs":300000}
{"level":"debug","msg":"install error encountered: encountered an error while validating receipt of data for mssql-server-integration-installer: timed out waiting for validation to succeed","time":"2023-01-23T08:01:30+07:00"}
{"level":"debug","msg":"Failed while executing and validating with progress for recipe name mssql-server-integration-installer, detail:encountered an error while validating receipt of data for mssql-server-integration-installer: timed out waiting for validation to succeed","time":"2023-01-23T08:01:30+07:00"}
{"level":"debug","msg":"error installing recipe mssql-server-integration-installer: encountered an error while validating receipt of data for mssql-server-integration-installer: timed out waiting for validation to succeed","time":"2023-01-23T08:01:30+07:00"}
{"error":"","guid":"","level":"debug","msg":"recipe event","recipe_name":"dotnet-agent-installer","status":"RECOMMENDED","statusCount":5,"tasks":null,"time":"2023-01-23T08:01:30+07:00","validationDurationMs":5273}
{"level":"debug","msg":"Done installing.","time":"2023-01-23T08:01:32+07:00"}
{"level":"debug","msg":"completed","time":"2023-01-23T08:01:32+07:00","timestamp":1674435692}
{"hasCanceledRecipes":false,"hasFailedRecipes":true,"hasInstalledRecipes":true,"hasSkippedRecipes":false,"level":"debug","msg":"final installation statuses updated","time":"2023-01-23T08:01:32+07:00"}
{"level":"fatal","msg":"accountID is required","time":"2023-01-23T08:14:51+07:00"}

level=debug msg="performing request" method=POST url="https://api.newrelic.com/graphql"
level=trace msg="request details" headers="{\"Api-Key\":[\"NRAK-CK8************************\"],\"Content-Type\":[\"appli
cation/json\"],\"Newrelic-Requesting-Services\":[\"newrelic-cli|newrelic-client-go\"],\"User-Agent\":[\"newrelic-cli/0.6
1.3 (https://github.com/newrelic/newrelic-cli)\"]}" query="mutation( $accountId: Int!, $installStatus: InstallationInsta
llStatusInput!, ) { installationCreateInstallStatus( accountId: $accountId, installStatus: $installStatus, ) { cliVersio
n enabledProxy error { details message } hostName installId installLibraryVersion isUnsupported kernelArch kernelVersion
 logFilePath os platform platformFamily platformVersion redirectUrl state targetedInstall } }" variables="{\"accountId\"
:3775626,\"installStatus\":{\"cliVersion\":\"0.61.3\",\"enabledProxy\":false,\"error\":{},\"hostName\":\"WJHQITSERVER2\"
,\"installId\":\"60ae1872-05dd-4cd4-854c-13606790b4b8\",\"installLibraryVersion\":\"0.63.5\",\"isUnsupported\":false,\"k
ernelArch\":\"x86_64\",\"kernelVersion\":\"6.3.9600 Build 9600\",\"logFilePath\":\"C:\\\\Users\\\\Administrator.WJHQITSE
RVER1\\\\.newrelic\\\\newrelic-cli.log\",\"os\":\"windows\",\"platform\":\"\",\"platformFamily\":\"\",\"platformVersion\
":\"6.3.9600 Build 9600\",\"redirectUrl\":\"https://onenr.io/07jb05Dqbwy\",\"state\":\"COMPLETED\",\"targetedInstall\":t
rue}}"

**Comment by fradvic** [comment]
There has been a few improvements released lately that mitigate the delay in confirming that the ingest is happening. It is still possible to get this error ("timed out waiting for validation to succeed") as either an occasional false positive (meaning the ingest got delayed beyond the timeout threshold) or due to a network issue.
