### ISSUE TITLE
Create Linux Memcached Recipe

### ISSUE THREAD

**Issue by rishimukhop1** [newrelic/open-install-library#86]
[ **Documentation** : https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/memcached-monitoring-integration](https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/memcached-monitoring-integration)<br/><br/> **Necessary Configuration**

- **Hostname:** Allow user to confirm default of localhost, or override default. NOTE: In this base configuration file the hostname is not listed as localhost even though the comments say that it should be. If the user confirms the default of localhost this recipe still needs to modify the YAML file to set host
- **Port:** Allow user to confirm default port of **11211** or override default.
- **Username:** Prompt user.` "Please enter your username if you are using authentication, else press [enter]`
- **Password** : Prompt User. "`"Please enter your password if you are using authentication, else press [enter]`

**For Logging:** Ensure that common log file directories/patterns & process name for Memcached is populated in the beginning of the recipe.

Aha! Link: https://newrelic.aha.io/features/VIRTUOSO-55

**Comment by JakubKotkowiak** [comment]
Hello @Julien4218 @devfreddy @jbeveland27, we've encountered an issue when the env variable has more than one word (separated by spaces) it causes the recipe to fail. Here's the link to the failed run: https://github.com/newrelic/open-install-library/pull/152/checks?check_run_id=1782699751
In addition a screenshot of the error has been attached below:
![Screenshot 2021-01-28 at 16 19 39](https://user-images.githubusercontent.com/52407257/106159139-c72b1980-6184-11eb-9cdb-de7f9441f108.png)

**Comment by jbeveland27** [comment]
Closed by https://github.com/newrelic/open-install-library/commit/c11b717dc4662bbfbbdd0cb06bd111f38e6f8fbc and https://github.com/newrelic/open-install-library/commit/211deae468297008810a6a64e9337eba62127fbd
