### ISSUE TITLE
Better K8 Version Detection

### ISSUE THREAD

**Issue by parisholley** [newrelic/open-install-library#871]
"This type of Kubernetes cluster is not supported by Pixie"

https://github.com/newrelic/open-install-library/blob/a0456eb881c02e1f06079d3de109227068b0b23e/recipes/newrelic/infrastructure/kubernetes.yml#L303-L305

```
kubectl version --short | grep "Server Version"
Server Version: v1.25.4
```

not running on a standard cloud vendor and it isn't validating based on version

**Comment by sanderblue** [comment]
Hi @parisholley, thanks for reporting this. We'll have a look and will triage accordingly 🙂

**Comment by xqi-nr** [comment]
Added more bugging info collection in this https://github.com/newrelic/open-install-library/pull/880
Close this issue
